sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install
