full_rebuild: true
incremental: true
destination: jekyllbuild
name: Material Theme
description: Material Theme for Jetbrains
url: https://mallowigi.github.io/material-theme-eap
baseurl: /docs
permalink: /:title/
paginate: 6
paginate_path: /page/:num
plugins: [jekyll-paginate]
infinite_scroll: false

tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'Posted by '
media_folder: /media/compressed
author_default_avatar: /profile-pic.jpeg

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-material-sidebar-left"
      type: "standard"
      homedisplay: "featimg"

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page-material-sidebar-left"
      author: "mallowigi"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, jekyllbuild, build, src]
