full_rebuild: true
incremental: true
source: "."
destination: "./jekyllbuild"
name: Material Theme
description: Material Theme for Jetbrains
url: https://mallowigi.github.io/material-theme-jetbrains-eap
baseurl: /
permalink: /:title/
paginate: 6
paginate_path: /page/:num
plugins: [jekyll-paginate]
infinite_scroll: false

tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'Posted by '
media_folder: /media/compressed
img_folder: /assets/img
author_default_avatar: /profile-pic.jpeg

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-material-sidebar-left"
      type: "standard"
      homedisplay: "featimg"

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page-material-sidebar-left"
      author: "mallowigi"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude:
  - .git
  - .gitignore
  - sass
  - js
  - .sass-cache
  - package.json
  - gruntfile.js
  - browser-sync.js
  - .postcssrc.js
  - node_modules
  - webpack.config.js
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - .eslintrc.js
  - .eslintignore
  - .editorconfig
  - .babelrc
  - LICENCE
  - README.md
  - jekyllbuild
  - build
  - src
sass:
  style: compressed
collections:
  features:
    permalink: /:collection/:title
    output: true
